classDiagram
    class Action {
        <<ValueObject>>
        +string name
    }
    class Concept {
        <<ValueObject>>
        +string name
        +SubjectType[] accepts
        +integer ttl
        +string description
    }
    class Outcome {
        <<ValueObject>>
        +string name
    }
    class Recipient {
        <<ValueObject>>
        +string name
    }
    class SubjectAttribute {
        <<ValueObject>>
        +string name
    }
    class SubjectType {
        <<ValueObject>>
        +string name
    }
